### ISSUE TITLE
unable to ssh into boot2docker

### ISSUE THREAD

**Issue by strowi** [docker/boot2docker#11]
Hi,

sorry if this has been explained somewhere else, but i couldn't find any documentation on this...

running ubuntu 15.04:
While i am able to successfully run `docker-machine create -d virtualbox --virtualbox-memory=2048 docker-vm`, i can't seem to get a working vm running build by `make boot2docker-virtualbox.iso`.

If i copy the resulting iso to ~/.docker/machine/cache/boot2docker.iso the vm is started, but docker-machine is unable to ssh into it... 

```
&{/usr/bin/ssh [/usr/bin/ssh -o PasswordAuthentication=no -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -i /home/strowi/.docker/machine/machines/docker-vm/id_rsa -p 42957 docker@localhost exit 0] []  <nil> <nil> <nil> [] <nil> <nil> <nil> <nil> false [] [] [] [] <nil>}
SSH cmd err, output: exit status 255: 
Error getting ssh command 'exit 0' : exit status 255
Getting to WaitForSSH function...
Testing TCP connection to: localhost:42957
Using SSH client type: external
About to run SSH command:
exit 0
...
```

Since i can manually run ssh and get a password-prompt, i guess this is a problem with the ssh-keys?
Can anyone verify this or help me out?

**Comment by tianon** [comment]
The ISO built from this repo isn't actually supported by `docker-machine` yet (the changes had to be reverted before the 0.4.0 release). :confused:

**Comment by strowi** [comment]
Ok, that explains a lot of my troubles. Thx for clearing things up! So i'll have to checkout boot2docker/boot2docker and figure out how to get my tools into that image.

**Comment by sebgoa** [comment]
@tianon Could you point us to the reverted commit ? I am running into the same issue.

**Comment by tianon** [comment]
https://github.com/docker/machine/pull/1640

**Comment by sebgoa** [comment]
ok thanks. so the current boot2docker.iso used in the latest docker-machine is the one from boot2docker/boot2docker ?

**Comment by tianon** [comment]
That is correct.

**Comment by sebgoa** [comment]
@tianon any thoughts to when this will be used in docker-machine ?

**Comment by tianon** [comment]
Definitely best to ask the maintainers of Docker Machine about that (as you did in https://github.com/docker/machine/pull/1640#issuecomment-148728717 :smile:).
