### ISSUE TITLE
Could not read CA certificate ... .boot2docker/certs/boot2docker-vm/ca.pem

### ISSUE THREAD

**Issue by IdanAdar** [docker/boot2docker#12]
Hi,

I wanted to start afresh so I removed **everything\* from **everywhere** and proceeded with installing Docker Toolbox.

Now I am getting the following: Could not read CA certificate "/Users/idanadar/.boot2docker/certs/boot2docker-vm/ca.pem": open /Users/idanadar/.boot2docker/certs/boot2docker-vm/ca.pem: no such file or directory

I understand the error, but I do not understand how to correct it.

**Comment by IdanAdar** [comment]
The issue was with my .bash_profile configuration. It should be like this:

#### DOCKER

export DOCKER_HOST=tcp://192.168.99.100:2376
export DOCKER_MACHINE_NAME=default
export DOCKER_TLS_VERIFY=1
export DOCKER_CERT_PATH=/Users/idanadar/.docker/machine/machines/default

**Comment by bdharrington7** [comment]
I'm having the same exact issue, but setting these variables didn't help. Running the toolbox 1.8.3

**Comment by jlucasps** [comment]
I removed my old docker configurations on my `~/.zshrc` and it worked. Thank you all

**Comment by jasine** [comment]
@jlucasps it works on my situation, thanks
