### ISSUE TITLE
ls in mounted directory shows Killed, tab kills container

### ISSUE THREAD

**Issue by klokoy** [docker/boot2docker#14]
I have a container that I start like this

``` bash
docker run --name frontend -p 8080:80 -v /path/to/html:/usr/share/nginx/html:ro -d nginx
```

In my html folder, I have a `bower_components` folder. Inside this, there is a folder `my_code` that is installed from GitHub. When I attach to the container and ´ls´ inside `my_code` it shows `Killed`.  If I navigate to the `bower_components` and type my and try to `tab` into the `my_code` folder, the attach session is stopped / killed. I can even delete the `my_code` folder and create a new empty directory with the same name and it behaves the same. The difference between `my_code`and the other folders in `bower_components` that works as expected is that `my_code` is installed from GitHub rather then the bower registry, like this:

```
   //bower.json:

   "my_code": "https://github.com/klokoy/my_code.git"
```

**Comment by thaJeztah** [comment]
Where exactly are you seeing "Killed"? Could this be the host running out of memory, resulting in the container being killed ("oom" killed)? If the container is exited, could you run

```
docker inspect -f "{{ json .State }}" frontend
```

To check if the container was killed by the kernel because the system ran out of memory? (you should see a "OOMKilled" entry in the output)

**Comment by klokoy** [comment]
I attached an screenshot where I did the following: 
- started the container 
- attached myself into it
- ls the areo_common folder => shows Killed
- tried to tab to autocomplete path => thrown out of container
- inspected the container

![screen shot 2015-10-01 at 15 02 39](https://cloud.githubusercontent.com/assets/973082/10221248/8703df12-684d-11e5-9db8-121766f65f8e.png)

**Comment by thaJeztah** [comment]
Ah, interesting. I did a quick search in the current boot2docker repo (this repository is for the "next" version of boot2docker), and this issue looks similar: https://github.com/boot2docker/boot2docker/issues/704

**Comment by klokoy** [comment]
I think you´r right. I did use bower link in the folder so symlinks had existed in the folder at an earlier stage. Removing them does not help. I´ll close this and keep an eye on https://github.com/boot2docker/boot2docker/issues/704

**Comment by thaJeztah** [comment]
Thanks @klokoy, I hope you're able to resolve it!
