### ISSUE TITLE
Provide kernel config

### ISSUE THREAD

**Issue by tiborvass** [docker/boot2docker#9]
I couldn't find the kernel configs anywhere inside the VM. Are they missing?

**Comment by tianon** [comment]
We don't compile our own kernel. :smile:

If you do something like "make explore-docker", kernel config should be
available inside "/boot".

**Comment by tiborvass** [comment]
I see, but why not provide that list of kernel options inside the VM? Is it reserved for when you compile your own kernel?

**Comment by tianon** [comment]
Yeah, it's getting excluded as a side effect -- if we narrow down our `/boot` exclusion (which is reasonable IMO) we should be able to get the kernel config included in the ISO.
